[server]
addr = "0.0.0.0:8043"

[sourcify]
api_url = "https://sourcify.dev/server/"
verification_attempts = 3
request_timeout = 10

[solidity]
refresh_versions_schedule = "0 0 * * * * *"
    [solidity.fetcher.list]
    compilers_list_url = "https://solc-bin.ethereum.org/linux-amd64/list.json"
